### ISSUE TITLE
Design: Create Logo

### ISSUE THREAD

**Issue by hd2802** [hd2802/ESP#73]
Create a Logo for the website.

This could be a designed graphical logo or even just the title of the website typed in a nice font.

Either way, please provide the files for the images either on the Discord server.

Please format the file in SVG, JPEG and PNG formats.

**Comment by shyam1112** [comment]
Hello, I hope you are fine. I will be ready to make that type of logo. Please give me some information related to your website. Like name of website or the motive of the website etc.
